### PR TITLE
Fix edit URL to point to GitHub instead of internal Phabricator

### PR DESCRIPTION
**Pull request by JoelMarcey**
Also update Docusaurus to latest version as well.

### CODE REVIEW

**Comment by JoelMarcey** [comment]
LOL - nevermind. Looks like @simonmar  beat me to the `editURL` fix.

If you want to do the upgrade to Beta.5 of Docusaurus, this still could apply after I resolve the `docusaurus.config.js` conflict, but I will close this for now. Reopen if you would like.

**Comment by JoelMarcey** [comment]
Although, @simonmar, you can append the `$docPath` to the URL so you can go straight to the page. That might make the experience better. See how I did that in my PR. Or I can land this with the fix too, after resolving against your fix. Your choice.

**Comment by simonmar** [comment]
@JoelMarcey want to rebase your PR and fix the conflict, then I'll import it?

**Comment by JoelMarcey** [comment]
Sure. I will do that in just a bit. 👍

**Comment by JoelMarcey** [comment]
@simonmar Here you go!

**Comment by simonmar** [comment]
Hey @JoelMarcey, I get a validation error with this, what am I doing wrong?

```
~/code/glean/glean/website > yarn start
yarn run v1.22.10
$ docusaurus start
Starting the development server...

A validation error occured.
The validation system was added recently to Docusaurus as an attempt to avoid user configuration errors.
We may have made some mistakes.
If you think your configuration is valid and should keep working, please open a bug report.

ValidationError: "editUrl" contains an invalid value
```

**Comment by JoelMarcey** [comment]
> Also the existing edit links do already point directly to the file in github, so I'm not sure if we need this?

Oh ok. I see that it works now. It wasn't pointing to the right place before. Unless I totally missed it. Then yeah, this is unnecessary. I will close the PR.

The update to the latest beta can be done separately.

**Pull request closed without merging**
